language: java
jdk: oraclejdk11

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "sandipan-sonar"
    token: $SONAR_TOKEN

script:
  - ./mvnw clean compile sonar:sonar -Pcoverage verify jib:build -Dbuild.number=$TRAVIS_BUILD_NUMBER -Ddocker.repo.name=$DOCKER_HUB_REPO_NAME -Ddocker.repo.key=$DOCKER_HUB_REPO_KEY

