language: java
jdk: oraclejdk11

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "sandipan-sonar"
    token: $SONAR_TOKEN

script:
  - ./mvnw clean verify sonar:sonar -Pcoverage
  - ./mvnw compile test jib:build -Dbuild.number=$TRAVIS_BUILD_NUMBER

