language: java
jdk: oraclejdk11

before_install:
  - chmod +x mvnw
services:
  - docker
addons:
  sonarcloud:
    organization: "sandipan-sonar"
    token: $SONAR_TOKEN

script:
  - ./mvnw clean compile sonar:sonar -Pcoverage verify jib:build
deploy:
  provider: script
  script: bash deploy.sh
  on:
branch: master

