sudo: required
language: java
jdk: oraclejdk11

env:
  global:
    - secure: "encrypted-sonar-token"
    - secure: "encrypted-dockerhub-username"
    - secure: "encrypted-dockerhub-password"
    - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "sandipan-sonar"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw compile test jib:build -Dbuild.number=${env.BUILD_NUMBER}
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

