language: java
jdk: oraclejdk11

before_install:
  - chmod +x mvnw
services:
  - docker
addons:
  sonarcloud:
    organization: "dhobighat"
    token: $SONAR_TOKEN
script:
  - echo "$DOCKER_HUB_REPO_KEY" | docker login -u "$DOCKER_HUB_REPO_NAME" --password-stdin
  - ./mvnw clean compile jib:build sonar:sonar -Pcoverage verify
deploy:
  provider: script
  script: bash deploy.sh
  on:
branch: master

