spring:
  application:
  name: dashboard-service
  profiles:
    active:
    - dev
  main:
    banner-mode: off

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://dashboard-user:QAJkmB9mJuFxRoes@dhobighat-dev-db-cluster.cap7l.mongodb.net/dashboard-service-db
server:
  port: 8000

---

spring:
  profiles: production
server:
  port: 8000


