spring:
  application:
  name: dashboard-service
  profiles:
    active:
    - dev
  main:
    banner-mode: off

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://mongo_db_user:VnjNuLeRlz3x1rRa@dhobighat-dev-cluster.umwfh.mongodb.net/dashboard-service
server:
  port: 8000

---

spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb+srv://mongo_db_user:VnjNuLeRlz3x1rRa@dhobighat-prod-cluster.umwfh.mongodb.net/dashboard-service
server:
  port: 8000


