version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test

jobs:
  unit-test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dashboard-service-{{ checksum "pom.xml" }}
            - dashboard-service
      - run: mvn dependency:go-offline
      - run:
          name: Build and unit test
          command: |
            mvn test -B \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME}
      - save_cache:
          paths:
            - ~/.m2
          key: dashboard-service-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports



  publish-docker:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dashboard-service-{{ checksum "pom.xml" }}
            - dashboard-service
      - run: mvn dependency:go-offline
      - run:
          name: Publish Docker image with Jib
          command: |
            mvn compile jib:build -B -DskipTests=true \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME}
